# Generated by Django 2.1.7 on 2019-04-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('payments', '0002_auto_20190331_2037'), ('payments', '0003_auto_20190401_0040')]

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='funds_low',
            field=models.BooleanField(default=False, verbose_name='Deposits are currently stuck due to low balance?'),
        ),
        migrations.AddField(
            model_name='coin',
            name='last_notified',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Email Notification'),
        ),
        migrations.AddField(
            model_name='coin',
            name='notify_low_funds',
            field=models.BooleanField(default=False, verbose_name='Send an email notification if wallet balance low?'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='convert_dest_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='convert_dest_memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='last_convert_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Conversion Attempt'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('err', 'Error Processing Transaction'), ('inv', 'Transaction is invalid'), ('refund', 'Coins were returned to user'), ('new', 'New (awaiting processing)'), ('mapped', 'Destination data found. Awaiting conversion.'), ('conv', 'Successfully converted')], default='new', max_length=20),
        ),
    ]
