# Generated by Django 2.1.7 on 2019-04-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_coin_lowfunds_20190401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressaccountmap',
            name='deposit_address',
            field=models.CharField(max_length=255, verbose_name='Deposit Address / Account'),
        ),
        migrations.AlterField(
            model_name='addressaccountmap',
            name='deposit_memo',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Deposit Memo (if required)'),
        ),
        migrations.AlterField(
            model_name='addressaccountmap',
            name='destination_address',
            field=models.CharField(max_length=255, verbose_name='Destination Address / Account'),
        ),
        migrations.AlterField(
            model_name='addressaccountmap',
            name='destination_memo',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Destination Memo (if required)'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='to_memo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Destination Memo (if applicable)'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='convert_dest_memo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='from_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='memo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='refund_memo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='to_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
