# Generated by Django 2.1.7 on 2019-05-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190403_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoKeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(db_index=True, max_length=255, verbose_name='Network for the key (e.g. steem, eos)')),
                ('private_key', models.CharField(max_length=1000, verbose_name='Private Key (format varies per network)')),
                ('public_key', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username / Wallet (if required)')),
                ('key_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Key Type (e.g. owner / active)')),
                ('balance', models.DecimalField(decimal_places=20, default=0, max_digits=40)),
            ],
        ),
    ]
