# Generated by Django 2.1.9 on 2019-07-06 15:21

from django.db import migrations, models


def set_coin_id(apps, schema_editor):
    Coin = apps.get_model('payments', 'Coin')
    for coin in Coin.objects.all().iterator():
        print(f'Updating symbol_id for {coin.symbol}')
        coin.symbol_id = coin.symbol
        coin.save()
        print(f'Updated {coin.symbol}.')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_cryptokeypair_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='symbol_id',
            field=models.CharField(default='ignorethis', max_length=30, verbose_name='Native Coin Symbol (e.g. BTC)'),
            preserve_default=False,
        ),
        migrations.RunPython(set_coin_id),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=30, primary_key=True, serialize=False,
                                   verbose_name='Unique Coin Symbol (for API usage)'),
        ),
    ]
