# Generated by Django 2.2.6 on 2019-10-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20191009_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='convert_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_converts', to='payments.Coin'),
        ),
    ]
