# Generated by Django 2.2.6 on 2019-10-10 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20191009_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Task Method being ran')),
                ('task_read', models.BooleanField(default=False, verbose_name='Has the task been loaded and output/errors handled?')),
                ('queued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='What/who queued this task?')),
                ('metadata', models.TextField(default='{}', max_length=2000, verbose_name='Task Metadata (JSON)')),
                ('error_log', models.TextField(blank=True, max_length=2000, null=True)),
                ('task_id', models.CharField(max_length=255, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Conversion')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Deposit')),
            ],
        ),
    ]
