# Generated by Django 2.2.23 on 2023-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayout',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
