# Generated by Django 3.2.19 on 2023-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feepayout_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
