# Generated by Django 3.2.19 on 2026-09-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feepayout_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayout',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Latest Exception'),
        ),
    ]
